PlayerCosmetics:
  1:
    name: '&eEar Cat'
    material: FEATHER
    modeldata: 12
    lore:
      - ""
      - "&6&nExample"
  2:
    name: '&eBlack Wing'
    material: FEATHER
    modeldata: 18
    lore:
      - ""
      - "&6&nExample"
  3:
    name: '&eDragon Wing'
    material: FEATHER
    modeldata: 22
    lore:
      - ""
      - "&6&nExample"
  4:
    name: '&eTail'
    material: FEATHER
    modeldata: 20
    lore:
      - ""
      - "&6&nExample"