name: PlayerCosmetics
version: 1.3
main: com.josemarcellio.playercosmetics.PlayerCosmetics
authors: [JoseMarcellio]
description: PlayerCosmetics plugin

commands:
  playercosmeticsgive:
    aliases: [pcg, cosmeticsgive]
    description: Give Cosmetics
  playercosmeticsreload:
    aliases: [pcr, cosmeticsreload]
    description: Reload Cosmetics
  playercosmeticsset:
    aliases: [pcs, cosmeticsset]
    description: Set Cosmetics
