name: PlayerCosmetics
version: 1.4
main: com.josemarcellio.playercosmetics.PlayerCosmetics
authors: [JoseMarcellio]
description: PlayerCosmetics plugin

commands:
  playercosmetics:
    aliases: [pcs, cosmeticsset]
    description: Set Cosmetics